# Generated by Django 5.1.6 on 2025-03-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitorCount',
            new_name='VideoCount',
        ),
        migrations.AlterModelOptions(
            name='videocount',
            options={},
        ),
    ]
